import Head from "next/head";
import Radio from "@/components/Radio";

export default function Home() {
  return (
    <>
      <Head>
        <title>Super Radio | DreamsOfImran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App">
          <h1>Super-Duper Radio Player</h1>
          <h2>Pick a language, choose a station, start listening!</h2>
          <Radio />
        </div>
      </main>
    </>
  );
}
